on: [push]

permissions:
  contents:  write
jobs:
  test:
    runs-on: ubuntu-latest
    name: Publish Logseq graph
    steps:
      - uses: actions/checkout@v3
      - uses: logseq/publish-spa@main
      - name: add a nojekyll file
        run: touch $GITHUB_WORKSPACE/www/.nojeklly
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: www
